name: 'Get Next Version'
description: 'Gets next version based on previous tag'
branding:
  icon: 'tag'
  color: 'gray-dark'
outputs:
  tag:
    description: 'Latest tag'
runs:
  using: 'node12'
  main: 'main.js'
